name: Check Available Qt Versions

on:
  workflow_dispatch:

jobs:
  qt-list:
    runs-on: windows-2022

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install aqtinstall
        run: python -m pip install --upgrade pip aqtinstall

      - name: Check aqtinstall version
        run: python -m aqt version

      - name: List Qt versions (Windows desktop)
        run: python -m aqt list-qt windows desktop

      - name: Filter Qt 6.x
        run: python -m aqt list-qt windows desktop | findstr 6

      - name: Filter MSVC builds
        run: python -m aqt list-qt windows desktop | findstr msvc
