name: Check Available Qt Versions (Windows)

on:
  workflow_dispatch:

jobs:
  qt-list:
    runs-on: windows-2022

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: List ALL Qt versions (Windows Desktop)
        run: python -m aqt list-qt windows desktop

      - name: Filter Qt 6.x only
        run: python -m aqt list-qt windows desktop | findstr 6.

      - name: Filter MSVC-related builds
        run: python -m aqt list-qt windows desktop | findstr msvc
